apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmm-service-debt-deployment
  labels:
    app: gmm-service-debt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmm-service-debt
  template:
    metadata:
      labels:
        app: gmm-service-debt
    spec:
      containers:
        - name: gmm-service-debt
          image: npmoewii/gmm-service-debt
          ports:
            - containerPort: 7001
          env:
            - name: DB_HOST
              value: '127.0.0.1'
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              value: 'gmm_transaction'
            - name: DB_PASSWORD
              value: 'gmm_transaction_password'
            - name: DB_NAME
              value: 'gmm_transaction'
            - name: DEBT_PORT
              value: '7001'
            - name: USER_BASE_ADDRESS
              value: 'http://192.168.0.100/api/user'
