apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmm-service-user-deployment
  labels:
    app: gmm-service-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmm-service-user
  template:
    metadata:
      labels:
        app: gmm-service-user
    spec:
      containers:
        - name: gmm-service-user
          image: npmoewii/gmm-service-user:rpi
          ports:
            - containerPort: 7000
          env:
            - name: MYSQL_HOST
              value: '192.168.0.100'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: 'gmm_user'
            - name: MYSQL_PASSWORD
              value: 'gmm_user_password'
            - name: MYSQL_DATABASE
              value: 'gmm_user'
            - name: PORT
              value: '7000'
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
