apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmm-frontend-deployment
  labels:
    app: gmm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmm-frontend
  template:
    metadata:
      labels:
        app: gmm-frontend
    spec:
      containers:
        - name: gmm-frontend
          image: npmoewii/gmm-frontend:rpi
          ports:
            - containerPort: 80
          env:
            - name: API_USER
              value: 'http://192.168.0.100/api/user/'
            - name: API_DEBT
              value: 'http://192.168.0.100/api/debt/'
            - name: API_TRANSACTION
              value: 'http://192.168.0.100/api/transaction/'
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
