apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmm-service-user-deployment
  labels:
    app: gmm-service-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmm-service-user
  template:
    metadata:
      labels:
        app: gmm-service-user
    spec:
      containers:
        - name: gmm-service-user
          image: npmoewii/gmm-service-user
          ports:
            - containerPort: 7000
          env:
            - name: MYSQL_HOST
              value: '127.0.0.1'
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USER
              value: 'gmm_user'
            - name: MYSQL_PASSWORD
              value: 'gmm_user_password'
            - name: MYSQL_DATABASE
              value: 'gmm_user'
            - name: PORT
              value: '7000'
