apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmm-database-deployment
  labels:
    app: gmm-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmm-database
  template:
    metadata:
      labels:
        app: gmm-database
    spec:
      containers:
        - name: gmm-database
          image: npmoewii/gmm-database
          ports:
            - containerPort: 3306
          args:
            ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
