apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmm-service-transaction-deployment
  labels:
    app: gmm-service-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmm-service-transaction
  template:
    metadata:
      labels:
        app: gmm-service-transaction
    spec:
      containers:
        - name: gmm-service-transaction
          image: npmoewii/gmm-service-transaction:rpi
          ports:
            - containerPort: 7002
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "gmm_transaction"
            - name: DB_PASSWORD
              value: "gmm_transaction_password"
            - name: DB_NAME
              value: "gmm_transaction"
            - name: DEBT_PORT
              value: "7002"
            - name: USER_BASE_ADDRESS
              value: "http://localhost:7000/"
