apiVersion: v1
kind: Service
metadata:
  name: gmm-service-transaction-service
spec:
  type: NodePort
  selector:
    app: gmm-service-transaction
  ports:
    - protocol: TCP
      port: 7002
      nodePort: 31997
