apiVersion: v1
kind: Service
metadata:
  name: gmm-service-debt-service
spec:
  type: NodePort
  selector:
    app: gmm-service-debt
  ports:
    - protocol: TCP
      port: 7001
      nodePort: 31998
